create table if not exists public.service_categories (
  id integer generated by default as identity primary key,
  parent_id integer references public.service_categories(id) on delete cascade,
  name varchar(160) not null,
  slug varchar(180) not null unique,
  description text not null default '',
  image text not null default '',
  display_order integer not null default 0,
  is_visible boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists service_categories_parent_id_idx on public.service_categories(parent_id);
create index if not exists service_categories_visibility_order_idx on public.service_categories(is_visible, display_order);

alter table public.service_categories enable row level security;
grant all on public.service_categories to postgres;

do $$
begin
  if exists (select 1 from pg_roles where rolname = 'anon') then
    execute 'revoke all on public.service_categories from anon';
  end if;
  if exists (select 1 from pg_roles where rolname = 'authenticated') then
    execute 'revoke all on public.service_categories from authenticated';
  end if;
  if exists (select 1 from pg_roles where rolname = 'service_role') then
    execute 'grant all on public.service_categories to service_role';
  end if;
end;
$$;
