-- Launch schema for Auto And All Automotive.
-- Safe to run after 0001_service_categories.sql.

create or replace function public.set_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists service_categories_set_updated_at on public.service_categories;
create trigger service_categories_set_updated_at
before update on public.service_categories
for each row execute function public.set_updated_at();

create table if not exists public.inventory_parts (
  id bigint generated by default as identity primary key,
  sku varchar(120) not null unique,
  part_name varchar(240) not null,
  category varchar(160) not null default '',
  interchange_number varchar(160) not null default '',
  picture_display_number varchar(120) not null default '',
  donor_stock varchar(80) not null default '',
  vin varchar(17) not null default '',
  vehicle_year varchar(4) not null default '',
  make varchar(100) not null default '',
  model varchar(120) not null default '',
  trim varchar(120) not null default '',
  series varchar(120) not null default '',
  production_date varchar(7) not null default '',
  engine varchar(160) not null default '',
  drivetrain varchar(80) not null default '',
  transmission varchar(160) not null default '',
  body_style varchar(120) not null default '',
  vehicle_type varchar(120) not null default '',
  fuel_type varchar(80) not null default '',
  assembly_plant text not null default '',
  mileage integer,
  factory_color varchar(120) not null default '',
  oem_paint_code varchar(80) not null default '',
  custom_paint_code varchar(80) not null default '',
  paint_system varchar(120) not null default '',
  custom_paint_name varchar(160) not null default '',
  custom_color_number varchar(100) not null default '',
  additive_formula jsonb not null default '[]'::jsonb,
  paint_notes text not null default '',
  condition_rating smallint check (condition_rating between 1 and 10),
  shelf_location varchar(120) not null default '',
  quantity integer not null default 0 check (quantity >= 0),
  reorder_point integer not null default 0 check (reorder_point >= 0),
  unit_cost numeric(12,2) not null default 0 check (unit_cost >= 0),
  retail_price numeric(12,2) not null default 0 check (retail_price >= 0),
  package_weight_lb numeric(10,2),
  package_length_in numeric(10,2),
  package_width_in numeric(10,2),
  package_height_in numeric(10,2),
  photo_gallery jsonb not null default '[]'::jsonb,
  data_source text not null default 'Manual entry',
  status varchar(40) not null default 'In stock' check (status in ('In stock','Low stock','Out of stock','Reserved','Sold','Archived')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint inventory_parts_vin_format check (vin = '' or vin ~ '^[A-HJ-NPR-Z0-9]{17}$')
);

create index if not exists inventory_parts_donor_stock_idx on public.inventory_parts(donor_stock);
create index if not exists inventory_parts_vin_idx on public.inventory_parts(vin) where vin <> '';
create index if not exists inventory_parts_category_idx on public.inventory_parts(category);
create index if not exists inventory_parts_location_idx on public.inventory_parts(shelf_location);
create index if not exists inventory_parts_status_idx on public.inventory_parts(status);

drop trigger if exists inventory_parts_set_updated_at on public.inventory_parts;
create trigger inventory_parts_set_updated_at
before update on public.inventory_parts
for each row execute function public.set_updated_at();

create table if not exists public.paint_formula_records (
  id bigint generated by default as identity primary key,
  inventory_part_id bigint references public.inventory_parts(id) on delete set null,
  pnc_number varchar(80) not null default '',
  vin varchar(17) not null default '',
  make varchar(100) not null default '',
  model varchar(120) not null default '',
  oem_paint_code varchar(80) not null default '',
  custom_paint_code varchar(80) not null default '',
  paint_system varchar(120) not null default '',
  factory_color varchar(120) not null default '',
  custom_paint_name varchar(160) not null default '',
  custom_color_number varchar(100) not null default '',
  additives jsonb not null default '[]'::jsonb,
  notes text not null default '',
  checklist jsonb not null default '{}'::jsonb,
  mixed_by varchar(160) not null default '',
  approved_by varchar(160) not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint paint_formula_vin_format check (vin = '' or vin ~ '^[A-HJ-NPR-Z0-9]{17}$')
);

drop trigger if exists paint_formula_records_set_updated_at on public.paint_formula_records;
create trigger paint_formula_records_set_updated_at
before update on public.paint_formula_records
for each row execute function public.set_updated_at();

create table if not exists public.estimate_requests (
  id bigint generated by default as identity primary key,
  reference_number varchar(80) unique,
  customer_name varchar(180) not null,
  phone varchar(40) not null default '',
  email varchar(254) not null default '',
  preferred_contact varchar(20) not null default 'phone' check (preferred_contact in ('phone','email','text')),
  vehicle_year varchar(4) not null default '',
  vehicle_make varchar(100) not null default '',
  vehicle_model varchar(120) not null default '',
  vin varchar(17) not null default '',
  pnc_number varchar(80) not null default '',
  service_type varchar(120) not null default '',
  damage_description text not null default '',
  photo_urls jsonb not null default '[]'::jsonb,
  status varchar(40) not null default 'New' check (status in ('New','Reviewing','Scheduled','Approved','Declined','Completed','Archived')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint estimate_contact_required check (phone <> '' or email <> ''),
  constraint estimate_vin_format check (vin = '' or vin ~ '^[A-HJ-NPR-Z0-9]{17}$')
);

create index if not exists estimate_requests_customer_idx on public.estimate_requests(lower(customer_name));
create index if not exists estimate_requests_vehicle_idx on public.estimate_requests(vehicle_year, vehicle_model);
create index if not exists estimate_requests_pnc_idx on public.estimate_requests(pnc_number);
create index if not exists estimate_requests_status_created_idx on public.estimate_requests(status, created_at desc);

drop trigger if exists estimate_requests_set_updated_at on public.estimate_requests;
create trigger estimate_requests_set_updated_at
before update on public.estimate_requests
for each row execute function public.set_updated_at();

create table if not exists public.contact_requests (
  id bigint generated by default as identity primary key,
  customer_name varchar(180) not null,
  phone varchar(40) not null default '',
  email varchar(254) not null default '',
  subject varchar(200) not null default '',
  message text not null,
  status varchar(30) not null default 'New' check (status in ('New','Contacted','Closed','Spam')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint contact_method_required check (phone <> '' or email <> '')
);

drop trigger if exists contact_requests_set_updated_at on public.contact_requests;
create trigger contact_requests_set_updated_at
before update on public.contact_requests
for each row execute function public.set_updated_at();

create table if not exists public.site_settings (
  setting_key varchar(120) primary key,
  setting_value jsonb not null,
  description text not null default '',
  updated_at timestamptz not null default now()
);

drop trigger if exists site_settings_set_updated_at on public.site_settings;
create trigger site_settings_set_updated_at
before update on public.site_settings
for each row execute function public.set_updated_at();

-- Administrative data is server-only. The Vercel application connects with
-- DATABASE_URL; no browser receives database credentials.
alter table public.inventory_parts enable row level security;
alter table public.paint_formula_records enable row level security;
alter table public.estimate_requests enable row level security;
alter table public.contact_requests enable row level security;
alter table public.site_settings enable row level security;

grant all on public.inventory_parts to postgres;
grant all on public.paint_formula_records to postgres;
grant all on public.estimate_requests to postgres;
grant all on public.contact_requests to postgres;
grant all on public.site_settings to postgres;
grant usage, select on all sequences in schema public to postgres;

do $$
begin
  if exists (select 1 from pg_roles where rolname = 'anon') then
    execute 'revoke all on public.inventory_parts, public.paint_formula_records, public.estimate_requests, public.contact_requests, public.site_settings from anon';
  end if;
  if exists (select 1 from pg_roles where rolname = 'authenticated') then
    execute 'revoke all on public.inventory_parts, public.paint_formula_records, public.estimate_requests, public.contact_requests, public.site_settings from authenticated';
  end if;
  if exists (select 1 from pg_roles where rolname = 'service_role') then
    execute 'grant all on public.inventory_parts, public.paint_formula_records, public.estimate_requests, public.contact_requests, public.site_settings to service_role';
    execute 'grant usage, select on all sequences in schema public to service_role';
  end if;
end;
$$;

-- Launch settings contain public business facts only.
insert into public.site_settings (setting_key, setting_value, description) values
  ('business_name', '"Auto And All Automotive"'::jsonb, 'Public business name'),
  ('address', '{"street":"1050 US Highway 158 E","city":"Sunbury","state":"NC","postal_code":"27979"}'::jsonb, 'Public shop address'),
  ('business_hours', '{"monday_friday":"9:00 AM–6:00 PM","saturday":"9:00 AM–5:00 PM","sunday":"Closed"}'::jsonb, 'Public operating hours'),
  ('contact_email', '"contact@autoandallautomotive.com"'::jsonb, 'Public contact email')
on conflict (setting_key) do update
set setting_value = excluded.setting_value,
    description = excluded.description,
    updated_at = now();

-- Idempotent launch categories and subcategories.
insert into public.service_categories (name, slug, description, image, display_order, is_visible) values
  ('Collision & Body', 'body-shop', 'Collision, structural and cosmetic body repair.', '/collision-photo-header.png', 1, true),
  ('Custom Paint', 'custom-paint', 'Color changes, graphics and specialty refinishing.', '/hero-auto-shop.png', 2, true),
  ('Auto Service', 'auto-service', 'Diagnostics, maintenance and mechanical repair.', '/service-writer-header.png', 3, true),
  ('Online Photo Estimate', 'estimate', 'Begin an estimate with vehicle and damage photos.', '/estimator-header.png', 4, true)
on conflict (slug) do update
set name = excluded.name,
    description = excluded.description,
    image = excluded.image,
    display_order = excluded.display_order,
    is_visible = excluded.is_visible,
    updated_at = now();

insert into public.service_categories (parent_id, name, slug, description, display_order, is_visible)
select p.id, v.name, v.slug, v.description, v.display_order, true
from (
  values
    ('body-shop', 'Collision Repair', 'body-shop-collision-repair', 'Collision repair planning and restoration.', 1),
    ('body-shop', 'Frame & Structural Repair', 'body-shop-frame-structural-repair', 'Structural measuring and repair.', 2),
    ('body-shop', 'Dent & Panel Repair', 'body-shop-dent-panel-repair', 'Panel repair and replacement.', 3),
    ('body-shop', 'Paint Matching & Blending', 'body-shop-paint-matching-blending', 'Color matching and adjacent-panel blending.', 4),
    ('custom-paint', 'Complete Color Changes', 'custom-paint-complete-color-changes', 'Complete refinishing and color-change projects.', 1),
    ('custom-paint', 'Custom Graphics & Stripes', 'custom-paint-custom-graphics-stripes', 'Custom graphics, accents and striping.', 2),
    ('custom-paint', 'Pearl & Metallic Finishes', 'custom-paint-pearl-metallic-finishes', 'Pearl, metallic and specialty paint systems.', 3),
    ('custom-paint', 'Restoration Refinishing', 'custom-paint-restoration-refinishing', 'Refinishing for restoration projects.', 4),
    ('auto-service', 'Computer Diagnostics', 'auto-service-computer-diagnostics', 'Vehicle system scanning and diagnosis.', 1),
    ('auto-service', 'Scheduled Maintenance', 'auto-service-scheduled-maintenance', 'Mileage- and time-based maintenance.', 2),
    ('auto-service', 'Brake Service', 'auto-service-brake-service', 'Brake inspection, repair and replacement.', 3),
    ('auto-service', 'Steering & Suspension', 'auto-service-steering-suspension', 'Steering and suspension diagnosis and repair.', 4),
    ('auto-service', 'Cooling & Engine Repair', 'auto-service-cooling-engine-repair', 'Cooling-system and engine repair.', 5),
    ('estimate', 'Collision Photo Estimate', 'estimate-collision-photo-estimate', 'Preliminary collision estimate request.', 1),
    ('estimate', 'Paint Project Request', 'estimate-paint-project-request', 'Custom paint and refinishing request.', 2),
    ('estimate', 'Mechanical Service Request', 'estimate-mechanical-service-request', 'Mechanical service and diagnostic request.', 3)
) as v(parent_slug, name, slug, description, display_order)
join public.service_categories p on p.slug = v.parent_slug
on conflict (slug) do update
set parent_id = excluded.parent_id,
    name = excluded.name,
    description = excluded.description,
    display_order = excluded.display_order,
    is_visible = excluded.is_visible,
    updated_at = now();
