import type { Part } from "./types";

export const seedParts: Part[] = [
  {
    id: 1,
    sku: "AAA-BRK-1048",
    name: "Front Ceramic Brake Pad Set",
    category: "Brakes",
    year: "2019",
    make: "Honda",
    model: "Accord",
    trim: "LX",
    engine: "1.5L Turbo I4",
    drivetrain: "FWD",
    transmission: "CVT",
    vin: "1HGCV1F30KA014048",
    donorStock: "PNC4048",
    shelf: "A-03-02",
    stock: 12,
    reorder: 4,
    cost: 34.5,
    price: 69.95,
    status: "In stock",
  },
  {
    id: 2,
    sku: "AAA-LMP-2210",
    name: "LED Headlamp Assembly — LH",
    category: "Lighting",
    year: "2020",
    make: "Nissan",
    model: "Altima",
    trim: "SV",
    engine: "2.5L I4",
    drivetrain: "FWD",
    transmission: "CVT",
    vin: "1N4BL4BV7LC102210",
    donorStock: "PNC2210",
    shelf: "B-01-04",
    stock: 3,
    reorder: 4,
    cost: 138,
    price: 249,
    status: "Low stock",
  },
  {
    id: 3,
    sku: "AAA-FLT-0782",
    name: "Engine Air Filter",
    category: "Filters",
    year: "2021",
    make: "Toyota",
    model: "Camry",
    trim: "LE",
    engine: "2.5L I4",
    drivetrain: "FWD",
    transmission: "8-speed automatic",
    vin: "4T1C11AK6MU550782",
    donorStock: "PNC0782",
    shelf: "C-02-06",
    stock: 28,
    reorder: 8,
    cost: 8.25,
    price: 18.99,
    status: "In stock",
  },
  {
    id: 4,
    sku: "AAA-BDY-5107",
    name: "Front Bumper Cover",
    category: "Body & exterior",
    year: "2022",
    make: "Ford",
    model: "F-150",
    trim: "XLT",
    engine: "3.5L V6",
    drivetrain: "4WD",
    transmission: "10-speed automatic",
    vin: "1FTFW1E89NFA45107",
    donorStock: "PNC5107",
    shelf: "R-04-01",
    stock: 0,
    reorder: 2,
    cost: 172,
    price: 329,
    status: "Out of stock",
  },
  {
    id: 5,
    sku: "AAA-SUS-3181",
    name: "Complete Strut Assembly — RH",
    category: "Suspension",
    year: "2018",
    make: "Chevrolet",
    model: "Malibu",
    trim: "LT",
    engine: "1.5L Turbo I4",
    drivetrain: "FWD",
    transmission: "6-speed automatic",
    vin: "1G1ZD5ST7JF243181",
    donorStock: "PNC3181",
    shelf: "D-01-03",
    stock: 6,
    reorder: 3,
    cost: 78,
    price: 149.5,
    status: "In stock",
  },
];
